import Link from 'next/link';

export const metadata = {
  title: 'Cart',
  description: 'generated by Sebi',
};

export default function Cart() {
  return (
    <main>
      <div>
        <h1>Cart</h1>
      </div>

      <Link href="/cart/checkout">Checkout</Link>
    </main>
  );
}
