export const metadata = {
  title: 'Contact',
  description: 'generated by Sebi',
};

export default function Contact() {
  return (
    <main>
      <div>
        <h2>Contact</h2>
      </div>
      <div>
        <h3>If you have questions about our machines contact us</h3>
      </div>
    </main>
  );
}
