import Link from 'next/link';

export const metadata = {
  title: 'Products',
  description: 'generated by Sebi',
};

export default function Products() {
  return (
    <div>
      <h1>Our Products</h1>
      <Link href="/">Home</Link>
      <Link href="/contact">Contact</Link>
      <Link href="/products">Products</Link>
      <Link href="/cart">Cart</Link>
    </div>
  );
}
